package com.pojo;

public class Building {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column building.buildId
     *
     * @mbg.generated
     */
    private Long buildid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column building.buildName
     *
     * @mbg.generated
     */
    private String buildname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column building.buildTeacher
     *
     * @mbg.generated
     */
    private String buildteacher;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.buildId
     *
     * @return the value of building.buildId
     *
     * @mbg.generated
     */
    public Long getBuildid() {
        return buildid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.buildId
     *
     * @param buildid the value for building.buildId
     *
     * @mbg.generated
     */
    public void setBuildid(Long buildid) {
        this.buildid = buildid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.buildName
     *
     * @return the value of building.buildName
     *
     * @mbg.generated
     */
    public String getBuildname() {
        return buildname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.buildName
     *
     * @param buildname the value for building.buildName
     *
     * @mbg.generated
     */
    public void setBuildname(String buildname) {
        this.buildname = buildname == null ? null : buildname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.buildTeacher
     *
     * @return the value of building.buildTeacher
     *
     * @mbg.generated
     */
    public String getBuildteacher() {
        return buildteacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.buildTeacher
     *
     * @param buildteacher the value for building.buildTeacher
     *
     * @mbg.generated
     */
    public void setBuildteacher(String buildteacher) {
        this.buildteacher = buildteacher == null ? null : buildteacher.trim();
    }
}