package com.pojo;

public class Missing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missing.missId
     *
     * @mbg.generated
     */
    private Long missid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missing.missDate
     *
     * @mbg.generated
     */
    private String missdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missing.missName
     *
     * @mbg.generated
     */
    private String missname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missing.missSex
     *
     * @mbg.generated
     */
    private String misssex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missing.missClass
     *
     * @mbg.generated
     */
    private String missclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missing.missRoom
     *
     * @mbg.generated
     */
    private String missroom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missing.missNote
     *
     * @mbg.generated
     */
    private String missnote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missing.missBuilding
     *
     * @mbg.generated
     */
    private String missbuilding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missing.missTeacher
     *
     * @mbg.generated
     */
    private String missteacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missing.missUsername
     *
     * @mbg.generated
     */
    private String missusername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missing.missId
     *
     * @return the value of missing.missId
     *
     * @mbg.generated
     */
    public Long getMissid() {
        return missid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missing.missId
     *
     * @param missid the value for missing.missId
     *
     * @mbg.generated
     */
    public void setMissid(Long missid) {
        this.missid = missid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missing.missDate
     *
     * @return the value of missing.missDate
     *
     * @mbg.generated
     */
    public String getMissdate() {
        return missdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missing.missDate
     *
     * @param missdate the value for missing.missDate
     *
     * @mbg.generated
     */
    public void setMissdate(String missdate) {
        this.missdate = missdate == null ? null : missdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missing.missName
     *
     * @return the value of missing.missName
     *
     * @mbg.generated
     */
    public String getMissname() {
        return missname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missing.missName
     *
     * @param missname the value for missing.missName
     *
     * @mbg.generated
     */
    public void setMissname(String missname) {
        this.missname = missname == null ? null : missname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missing.missSex
     *
     * @return the value of missing.missSex
     *
     * @mbg.generated
     */
    public String getMisssex() {
        return misssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missing.missSex
     *
     * @param misssex the value for missing.missSex
     *
     * @mbg.generated
     */
    public void setMisssex(String misssex) {
        this.misssex = misssex == null ? null : misssex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missing.missClass
     *
     * @return the value of missing.missClass
     *
     * @mbg.generated
     */
    public String getMissclass() {
        return missclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missing.missClass
     *
     * @param missclass the value for missing.missClass
     *
     * @mbg.generated
     */
    public void setMissclass(String missclass) {
        this.missclass = missclass == null ? null : missclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missing.missRoom
     *
     * @return the value of missing.missRoom
     *
     * @mbg.generated
     */
    public String getMissroom() {
        return missroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missing.missRoom
     *
     * @param missroom the value for missing.missRoom
     *
     * @mbg.generated
     */
    public void setMissroom(String missroom) {
        this.missroom = missroom == null ? null : missroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missing.missNote
     *
     * @return the value of missing.missNote
     *
     * @mbg.generated
     */
    public String getMissnote() {
        return missnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missing.missNote
     *
     * @param missnote the value for missing.missNote
     *
     * @mbg.generated
     */
    public void setMissnote(String missnote) {
        this.missnote = missnote == null ? null : missnote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missing.missBuilding
     *
     * @return the value of missing.missBuilding
     *
     * @mbg.generated
     */
    public String getMissbuilding() {
        return missbuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missing.missBuilding
     *
     * @param missbuilding the value for missing.missBuilding
     *
     * @mbg.generated
     */
    public void setMissbuilding(String missbuilding) {
        this.missbuilding = missbuilding == null ? null : missbuilding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missing.missTeacher
     *
     * @return the value of missing.missTeacher
     *
     * @mbg.generated
     */
    public String getMissteacher() {
        return missteacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missing.missTeacher
     *
     * @param missteacher the value for missing.missTeacher
     *
     * @mbg.generated
     */
    public void setMissteacher(String missteacher) {
        this.missteacher = missteacher == null ? null : missteacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missing.missUsername
     *
     * @return the value of missing.missUsername
     *
     * @mbg.generated
     */
    public String getMissusername() {
        return missusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missing.missUsername
     *
     * @param missusername the value for missing.missUsername
     *
     * @mbg.generated
     */
    public void setMissusername(String missusername) {
        this.missusername = missusername == null ? null : missusername.trim();
    }
}