package com.pojo;

public class Outers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outers.outId
     *
     * @mbg.generated
     */
    private Long outid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outers.outDate
     *
     * @mbg.generated
     */
    private String outdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outers.outName
     *
     * @mbg.generated
     */
    private String outname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outers.outSex
     *
     * @mbg.generated
     */
    private String outsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outers.outClass
     *
     * @mbg.generated
     */
    private String outclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outers.outNote
     *
     * @mbg.generated
     */
    private String outnote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outers.outId
     *
     * @return the value of outers.outId
     *
     * @mbg.generated
     */
    public Long getOutid() {
        return outid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outers.outId
     *
     * @param outid the value for outers.outId
     *
     * @mbg.generated
     */
    public void setOutid(Long outid) {
        this.outid = outid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outers.outDate
     *
     * @return the value of outers.outDate
     *
     * @mbg.generated
     */
    public String getOutdate() {
        return outdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outers.outDate
     *
     * @param outdate the value for outers.outDate
     *
     * @mbg.generated
     */
    public void setOutdate(String outdate) {
        this.outdate = outdate == null ? null : outdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outers.outName
     *
     * @return the value of outers.outName
     *
     * @mbg.generated
     */
    public String getOutname() {
        return outname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outers.outName
     *
     * @param outname the value for outers.outName
     *
     * @mbg.generated
     */
    public void setOutname(String outname) {
        this.outname = outname == null ? null : outname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outers.outSex
     *
     * @return the value of outers.outSex
     *
     * @mbg.generated
     */
    public String getOutsex() {
        return outsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outers.outSex
     *
     * @param outsex the value for outers.outSex
     *
     * @mbg.generated
     */
    public void setOutsex(String outsex) {
        this.outsex = outsex == null ? null : outsex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outers.outClass
     *
     * @return the value of outers.outClass
     *
     * @mbg.generated
     */
    public String getOutclass() {
        return outclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outers.outClass
     *
     * @param outclass the value for outers.outClass
     *
     * @mbg.generated
     */
    public void setOutclass(String outclass) {
        this.outclass = outclass == null ? null : outclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outers.outNote
     *
     * @return the value of outers.outNote
     *
     * @mbg.generated
     */
    public String getOutnote() {
        return outnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outers.outNote
     *
     * @param outnote the value for outers.outNote
     *
     * @mbg.generated
     */
    public void setOutnote(String outnote) {
        this.outnote = outnote == null ? null : outnote.trim();
    }
}