package com.pojo;

public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomId
     *
     * @mbg.generated
     */
    private Long roomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomBuilding
     *
     * @mbg.generated
     */
    private String roombuilding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomNumber
     *
     * @mbg.generated
     */
    private String roomnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomPeople
     *
     * @mbg.generated
     */
    private String roompeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomPhone
     *
     * @mbg.generated
     */
    private String roomphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomId
     *
     * @return the value of room.roomId
     *
     * @mbg.generated
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomId
     *
     * @param roomid the value for room.roomId
     *
     * @mbg.generated
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomBuilding
     *
     * @return the value of room.roomBuilding
     *
     * @mbg.generated
     */
    public String getRoombuilding() {
        return roombuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomBuilding
     *
     * @param roombuilding the value for room.roomBuilding
     *
     * @mbg.generated
     */
    public void setRoombuilding(String roombuilding) {
        this.roombuilding = roombuilding == null ? null : roombuilding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomNumber
     *
     * @return the value of room.roomNumber
     *
     * @mbg.generated
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomNumber
     *
     * @param roomnumber the value for room.roomNumber
     *
     * @mbg.generated
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomPeople
     *
     * @return the value of room.roomPeople
     *
     * @mbg.generated
     */
    public String getRoompeople() {
        return roompeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomPeople
     *
     * @param roompeople the value for room.roomPeople
     *
     * @mbg.generated
     */
    public void setRoompeople(String roompeople) {
        this.roompeople = roompeople == null ? null : roompeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomPhone
     *
     * @return the value of room.roomPhone
     *
     * @mbg.generated
     */
    public String getRoomphone() {
        return roomphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomPhone
     *
     * @param roomphone the value for room.roomPhone
     *
     * @mbg.generated
     */
    public void setRoomphone(String roomphone) {
        this.roomphone = roomphone == null ? null : roomphone.trim();
    }
}