package com.pojo;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuId
     *
     * @mbg.generated
     */
    private Long stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuUsername
     *
     * @mbg.generated
     */
    private String stuusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuPassword
     *
     * @mbg.generated
     */
    private String stupassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuName
     *
     * @mbg.generated
     */
    private String stuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuSex
     *
     * @mbg.generated
     */
    private String stusex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuClass
     *
     * @mbg.generated
     */
    private String stuclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuRoom
     *
     * @mbg.generated
     */
    private String sturoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuBuilding
     *
     * @mbg.generated
     */
    private String stubuilding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuStatus
     *
     * @mbg.generated
     */
    private String stustatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuId
     *
     * @return the value of student.stuId
     *
     * @mbg.generated
     */
    public Long getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuId
     *
     * @param stuid the value for student.stuId
     *
     * @mbg.generated
     */
    public void setStuid(Long stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuUsername
     *
     * @return the value of student.stuUsername
     *
     * @mbg.generated
     */
    public String getStuusername() {
        return stuusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuUsername
     *
     * @param stuusername the value for student.stuUsername
     *
     * @mbg.generated
     */
    public void setStuusername(String stuusername) {
        this.stuusername = stuusername == null ? null : stuusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuPassword
     *
     * @return the value of student.stuPassword
     *
     * @mbg.generated
     */
    public String getStupassword() {
        return stupassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuPassword
     *
     * @param stupassword the value for student.stuPassword
     *
     * @mbg.generated
     */
    public void setStupassword(String stupassword) {
        this.stupassword = stupassword == null ? null : stupassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuName
     *
     * @return the value of student.stuName
     *
     * @mbg.generated
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuName
     *
     * @param stuname the value for student.stuName
     *
     * @mbg.generated
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuSex
     *
     * @return the value of student.stuSex
     *
     * @mbg.generated
     */
    public String getStusex() {
        return stusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuSex
     *
     * @param stusex the value for student.stuSex
     *
     * @mbg.generated
     */
    public void setStusex(String stusex) {
        this.stusex = stusex == null ? null : stusex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuClass
     *
     * @return the value of student.stuClass
     *
     * @mbg.generated
     */
    public String getStuclass() {
        return stuclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuClass
     *
     * @param stuclass the value for student.stuClass
     *
     * @mbg.generated
     */
    public void setStuclass(String stuclass) {
        this.stuclass = stuclass == null ? null : stuclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuRoom
     *
     * @return the value of student.stuRoom
     *
     * @mbg.generated
     */
    public String getSturoom() {
        return sturoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuRoom
     *
     * @param sturoom the value for student.stuRoom
     *
     * @mbg.generated
     */
    public void setSturoom(String sturoom) {
        this.sturoom = sturoom == null ? null : sturoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuBuilding
     *
     * @return the value of student.stuBuilding
     *
     * @mbg.generated
     */
    public String getStubuilding() {
        return stubuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuBuilding
     *
     * @param stubuilding the value for student.stuBuilding
     *
     * @mbg.generated
     */
    public void setStubuilding(String stubuilding) {
        this.stubuilding = stubuilding == null ? null : stubuilding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuStatus
     *
     * @return the value of student.stuStatus
     *
     * @mbg.generated
     */
    public String getStustatus() {
        return stustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuStatus
     *
     * @param stustatus the value for student.stuStatus
     *
     * @mbg.generated
     */
    public void setStustatus(String stustatus) {
        this.stustatus = stustatus == null ? null : stustatus.trim();
    }
}