package com.dao;

import com.pojo.Admins;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdminsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    int insert(Admins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    Admins selectByPrimaryKey(Long adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    List<Admins> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Admins record);

    Admins findAdminByup(@Param("username") String username, @Param("password") String password);
}