package com.dao;

import com.pojo.Building;

import java.util.List;

public interface BuildingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long buildid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building
     *
     * @mbg.generated
     */
    int insert(Building record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building
     *
     * @mbg.generated
     */
    Building selectByPrimaryKey(Long buildid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building
     *
     * @mbg.generated
     */
    List<Building> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Building record);

}