package com.dao;

import com.pojo.Missing;
import java.util.List;

public interface MissingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long missid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missing
     *
     * @mbg.generated
     */
    int insert(Missing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missing
     *
     * @mbg.generated
     */
    Missing selectByPrimaryKey(Long missid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missing
     *
     * @mbg.generated
     */
    List<Missing> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Missing record);

}