package com.dao;

import com.pojo.Room;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    int insert(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    Room selectByPrimaryKey(Long roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    List<Room> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Room record);



    void updateRoom(@Param("id") long id, @Param("build") String build, @Param("name") String name, @Param("people") String people, @Param("tel") String tel);

    void AddARoom(  @Param("build") String build,
                    @Param("room") String room,
                    @Param("people") String people,
                    @Param("tel") String tel);
}